# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-03 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20161103_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hourlyprecip',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='hourlyprecip',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
