# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-10 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20161103_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='NYearEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n', models.IntegerField()),
                ('duration_hours', models.IntegerField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('inches', models.FloatField()),
            ],
        ),
    ]
