# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-04 15:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RiverCso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_time', models.DateTimeField()),
                ('close_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='RiverOutfall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('lat', models.FloatField(null=True)),
                ('lon', models.FloatField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='rivercso',
            name='river_outfall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csos.RiverOutfall'),
        ),
    ]
