# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 11:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csos', '0002_lakeoutfall_lakereversal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lakereversal',
            name='close_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='lakereversal',
            name='open_date',
            field=models.DateTimeField(),
        ),
    ]
