# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-08 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasementFloodingEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('unit_type', models.CharField(choices=[('z', 'zip'), ('c', 'community'), ('w', 'ward')], max_length=1)),
                ('unit_id', models.CharField(max_length=20)),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='basementfloodingevent',
            unique_together=set([('date', 'unit_type', 'unit_id')]),
        ),
    ]
